version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinicpass
      POSTGRES_DB: clinic_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      # Синхронизируем код, но исключаем node_modules
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  db_data: